### PR TITLE
fix: fixed regex pattern to work with all playlist links

### PR DESCRIPTION
**Pull request by sbendalam**
Subject: playlist controller regex pattern fix relates to issue #82

### CODE REVIEW

**Comment by sumitkolhe** [comment]
Thanks for the fix :) can you add 2 tests, one for playlist/featured path and one for jiosaavn.com / saavn.com domain?

**Comment by saibendalam** [comment]
Okay

**Comment by saibendalam** [comment]
Tailwind CDN is down, We need to use other reliable CDN providers for tailwind!

**Comment by sumitkolhe** [comment]
@saibendalam looks good to me, can you remove package-lock.json? We're using bun so don't need to commit it, thanks

**Comment by saibendalam** [comment]
done

**Pull request merged**
